# syntax=docker/dockerfile:1.7.0

ARG VERSION

# --------------------------------------------------------------------------------------------------
# Builder Image
# --------------------------------------------------------------------------------------------------

FROM cytopia/ansible:${VERSION} as builder

ENV VERSION=${VERSION}
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=off
ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ENV PIP_DEFAULT_TIMEOUT=100

# Install deps and generate requirements file
RUN <<EOF
#!/bin/bash
set -eux

apk add --update --no-cache curl python3-dev py3-pip gcc musl-dev libffi-dev openssl-dev

echo "dnspython" > requirements.txt
echo "jmespath" >> requirements.txt

case "${VERSION}" in
	"2.5" | "2.6" | "2.7" | "2.8" | "2.9")
		echo "mitogen==0.2.10" >> requirements.txt
		;;
	*)
		echo "mitogen" >> requirements.txt
		;;
esac
EOF

# Install and run pex
RUN python -m pip install --no-cache-dir pex \
	&& pex -r requirements.txt -o /ansible_tools.pex

# --------------------------------------------------------------------------------------------------
# Final Image
# --------------------------------------------------------------------------------------------------

FROM cytopia/ansible:${VERSION} as production

# Define uid/gid and user/group names
ARG MY_USER=ansible
ARG MY_GROUP=ansible
ARG MY_UID=1000
ARG MY_GID=1000
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=off
ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ENV PIP_DEFAULT_TIMEOUT=100
ENV PATH="/usr/local/bin:${HOME}/.local/bin:/bin:/usr/bin:/usr/share/doc:$PATH"

# Add user and group
RUN <<EOF
#!/bin/bash
set -eux

if ! getent group "${MY_GROUP}" > /dev/null 2>&1; then
    addgroup -g "${MY_GID}" "${MY_GROUP}"
fi

if ! getent passwd "${MY_USER}" > /dev/null 2>&1; then
    adduser -h /home/ansible -s /bin/bash -G "${MY_GROUP}" -D -u "${MY_UID}" "${MY_USER}"
fi

# Create necessary directories and set permissions
mkdir -p /home/ansible/.gnupg /home/ansible/.ssh /etc/sudoers.d/
chown "${MY_USER}:${MY_GROUP}" /home/ansible/.gnupg /home/ansible/.ssh
chmod 0700 /home/ansible/.gnupg /home/ansible/.ssh
echo "$MY_USER ALL=(root) NOPASSWD:ALL" > "/etc/sudoers.d/$MY_USER"
chmod 0440 "/etc/sudoers.d/$MY_USER"
EOF

# Additional binaries
RUN apk add --no-cache \
	bash \
	git \
	gnupg \
	jq \
	openssh-client \
	sudo \
	yq

COPY --from=builder /ansible_tools.pex /usr/local/bin/ansible_tools
COPY docker-entrypoint.sh /docker-entrypoint.sh

WORKDIR /data

USER ${MY_USER}

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/bin/bash"]

# https://github.com/opencontainers/image-spec/blob/master/annotations.md
LABEL "maintainer"="cytopia <cytopia@everythingcli.org>"
LABEL "org.opencontainers.image.authors"="cytopia <cytopia@everythingcli.org>"
LABEL "org.opencontainers.image.vendor"="cytopia"
LABEL "org.opencontainers.image.licenses"="MIT"
LABEL "org.opencontainers.image.url"="https://github.com/cytopia/docker-ansible"
LABEL "org.opencontainers.image.documentation"="https://github.com/cytopia/docker-ansible"
LABEL "org.opencontainers.image.source"="https://github.com/cytopia/docker-ansible"
LABEL "org.opencontainers.image.ref.name"="Ansible ${VERSION} tools"
LABEL "org.opencontainers.image.title"="Ansible ${VERSION} tools"
LABEL "org.opencontainers.image.description"="Ansible ${VERSION} tools"
